django/django_movie/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
]

django/django_movie/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

django/django_movie/movies/models.py
from platform import release
from turtle import title
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    audience = models.IntegerField()
    release_date = models.DateField()
    genre = models.CharField(max_length=30)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()

django/django_movie/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

# Create your views here.
def index(request):
    movies = Movie.objects.order_by('-pk')
    context = {
        'movies': movies
    }
    return render(request, 'movies/index.html/', context)

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie
    }
    return render(request, 'movies/detail.html/', context)

def new(request):
    return render(request, 'movies/new.html/')

def create(request):
    title = request.POST.get('title')
    audience = request.POST.get('audience')
    release_date = request.POST.get('release_date')
    genre = request.POST.get('genre')
    score = request.POST.get('score')
    poster_url = request.POST.get('poster_url')
    description = request.POST.get('description')

    movie = Movie(title=title, audience=audience, release_date=release_date, genre=genre, score=score, poster_url=poster_url, description=description)
    movie.save()
    return redirect('movies:index')

def delete(request, pk):
    print('삭제')
    movie = Movie.objects.get(pk=pk)
    movie.delete()
    return redirect('movies:index')

def edit(request, pk):
    movie = Movie.objects.get(pk=pk)
    context = {
        'movie': movie
    }
    return render(request, 'movies/edit.html/', context)

def update(request, pk):
    movie = Movie.objects.get(pk=pk)
    movie.title = request.POST.get('title')
    movie.audience = request.POST.get('audience')
    movie.release_date = request.POST.get('release_date')
    movie.genre = request.POST.get('genre')
    movie.score = request.POST.get('score')
    movie.poster_url = request.POST.get('poster_url')
    movie.description = request.POST.get('description')
    movie.save()
    return redirect('movies:index')

django/django_movie/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}
    <h1>DETAIL</h1>
    <hr>
    <img src="{{movie.poster_url}}" alt="{{movie.poster_url}}">
    <br>
    <b>{{movie.title}}</b>
    <p>Audience : {{movie.audience}}</p>
    <p>Release Dates : {{movie.release_date}}</p>
    <p>Genre : {{movie.genre}}</p>
    <p>Score : {{movie.score}}</p>
    <p>{{movie.description}}</p>
    <a href="{% url 'movies:edit' movie.pk %}">[EDIT]</a>
    <br>
    <form action="{% url 'movies:delete' movie.pk %}" mothod="POST">
        <input type="submit" value='DELETE'>
    </form>
    <br>
    <a href="{% url 'movies:index' %}">[뒤로가기]</a>
{% endblock content %}

django/django_movie/movies/templates/movies/edit.html
{% extends 'base.html' %}
{% block content %}
    <h1>EDIT</h1>
    <hr>
    <form action="{% url 'movies:update' movie.pk %}" method="POST">
        {% csrf_token %}
        <label for="title">TITLE</label>
        <input type="text" name='title' id ='title' value='{{movie.title}}'>
        <br>
        <label for="audience">AUDIENCE</label>
        <input type="number" name='audience' id='audience' value='{{movie.audience}}'>
        <br>
        <label for="release_date">RELEASE_DATE</label>
        <input type="date" name='release_date' id='release_date' value="{{ movie.release_date|date:'Y-m-d' }}">
        <br>
        <label for="genre">GENRE</label>
        <select name="genre" id="genre" required >
            <option value="">선택</option>
            <option value="comedy" {% if movie.genre == "comedy" %}selected{% endif %}>comedy</option>
            <option value="horror" {% if movie.genre == "horror" %}selected{% endif %}>horror</option>
            <option value="drama" {% if movie.genre == "drama" %}selected{% endif %}>drama</option>
        </select>
        <br>
        <label for="score">SCORE</label>
        <input type="number" name='score' id='score' value='{{movie.score}}'>
        <br>
        <label for="poster_url">POSTER_URL</label>
        <input type="poster_url" name='poster_url' id='poster_url' value='{{movie.poster_url}}'>
        <br>
        <label for="description">DESCRIPTION</label>
        <textarea name="description" id='description' row= 30 col= 30>{{movie.description}}</textarea><br>
        <input type="reset" value='리셋'>
        <input type="submit" value='저장'>
    </form>
    <hr>
    <a href="{% url 'movies:detail' movie.pk %}">[뒤로가기]</a>
{% endblock content %}

django/django_movie/movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
    <h1>INDEX</h1>
    <a href="{% url 'movies:new' %}">[NEW]</a>
    <hr>
    {% for movie in movies %}
        <a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a>
        <p>{{movie.score}}</p>
        <hr>
    {% endfor %}
{% endblock content %}

django/django_movie/movies/templates/movies/new.html
{% extends 'base.html' %}
{% block content %}
    <h1>NEW</h1>
    <hr>
    <form action="{% url 'movies:create' %}" method="POST">
        {% csrf_token %}
        <label for="title">TITLE</label>
        <input type="text" name='title' id ='title'>
        <br>
        <label for="audience">AUDIENCE</label>
        <input type="number" name='audience' id='audience'>
        <br>
        <label for="release_date">RELEASE_DATE</label>
        <input type="date" name='release_date' id='release_date'>
        <br>
        <label for="genre">GENRE</label>
        <select name="genre" id="genre" required>
            <option value="">선택</option>
            <option value="comedy">comedy</option>
            <option value="horror">horror</option>
            <option value="drama">drama</option>
        </select>
        <br>
        <label for="score">SCORE</label>
        <input type="number" name='score' id='score'>
        <br>
        <label for="poster_url">POSTER_URL</label>
        <input type="poster_url" name='poster_url' id='release_date'>
        <br>
        <label for="description">DESCRIPTION</label>
        <textarea name="description" id='description' row= 30 col= 30></textarea><br>
        <input type="reset" value='리셋'>
        <input type="submit" value='저장'>
    </form>
    <hr>
    <a href="{% url 'movies:index' %}">[뒤로가기]</a>
{% endblock content %}

django/django_movie/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}
    
    {% endblock content %}
    
</body>
</html>